### ISSUE TITLE
Erro no console

### ISSUE THREAD

**Issue by ayukays** [thiagocodex/GetSpawners#2]
**Trigger**
Aparenta estar sendo causado quando um jogador quebra um Spawner

**Log**
```
[02:28:23 ERROR]: Could not pass event BlockBreakEvent to GetSpawners v1.0.5
java.lang.NullPointerException: null
[02:28:26 ERROR]: Could not pass event BlockBreakEvent to GetSpawners v1.0.5
java.lang.IllegalArgumentException: Cannot translate null text
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.16.5.jar:git-Paper-576]
        at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:354) ~[patched_1.16.5.jar:git-Paper-576]
        at me.thiagocodex.getspawners.customconfig.Messages.color(Messages.java:109) ~[?:?]
        at me.thiagocodex.getspawners.DropSpawners.onSpawnerMine(DropSpawners.java:38) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-576]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-576]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-576]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:358) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:317) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:283) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1634) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-576]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[02:28:28 ERROR]: Could not pass event BlockBreakEvent to GetSpawners v1.0.5
java.lang.NullPointerException: null
```

**Comment by thiagocodex** [comment]
Esse plugin foi testado de muitas formas e não reproduziu nenhum erro no console, isso pode ter sido causado por alguma alteração nos arquivos de configuração, para testá-lo, apenas exclua a pasta getspawners para gerar uma nova na inicialização do servidor, em seguida tente reproduzir o erro. Se o problema persistir entre em contato novamente com mais informações. Obrigado.
